name: docs

on:
  push:
    branches: [ master , dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pandoc and related packages
      run: |
        sudo apt update
        sudo apt install -y pandoc texlive-latex-extra texlive-science latexmk curl
    - name: Checkout submodules
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: E2020-myanswers
      run: |
        cd exam/2020
        pandoc E2020-myanswers.md -o E2020-myanswers.pdf
    - name: Upload E2020-myanswers
      uses: actions/upload-artifact@v2
      with:
        name: E2020-myanswers.pdf
        path: exam/2020/E2020-myanswers.pdf

    - name: E2020-sol
      run: |
        cd exam/2020/sol
        pandoc sol.md -o E2020-sol.pdf
    - name: Upload E2020-myanswers
      uses: actions/upload-artifact@v2
      with:
        name: E2020-sol.pdf
        path: exam/2020/sol/E2020-sol.pdf

    - name: T2018-myanswers
      run: |
        cd test/2018
        pandoc test2018-mysolution.md -o T2018-myanswers.pdf
    - name: Upload T2018-myanswers
      uses: actions/upload-artifact@v2
      with:
        name: T2018-myanswers.pdf
        path: test/2018/T2018-myanswers.pdf

    - name: T2018-sol
      run: |
        cd test/2018/sol
        pandoc sol.md -o T2018-sol.pdf
    - name: Upload T2018-sol
      uses: actions/upload-artifact@v2
      with:
        name: T2018-sol.pdf
        path: test/2018/sol/T2018-sol.pdf
